# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2239a3bcdbfe5edbca1b5be093ba82fcc4256752618ec66ea738b9b208e41bec0aea711c8832e8cf2b01915ff90fd198b19125f525c826f89634f820a732a680

test:
  secret_key_base: 10afd58469222eef8c41f0726f1098d3395210a2636af2591cb45e373f91d142b48ba4abbe19d45dd0e64a7371c1f309a9ffa16c8871ea03e19a9f2b03281ce7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
